// This file was auto-generated by ML.NET Model Builder. 

using System;
using TIS_NTHUML.Model;

namespace TIS_NTHUML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                VBmaxWD_F1 = 1177.93F,
                VBmaxWD_F2 = 2195.55F,
                VBmaxWD_F3 = 2564.96F,
                VBmaxWD_F4 = 2564.96F,
                VBsumWD_F1 = 8855099F,
                VBsumWD_F2 = 1.584147E+07F,
                VBsumWD_F3 = 1.651457E+07F,
                VBsumWD_F4 = 1.61908E+07F,
                VBWL_F1 = 5615.81F,
                VBWL_F2 = 5615.81F,
                VBWL_F3 = 5427.36F,
                VBWL_F4 = 5615.81F,
                CHnum_F1 = 706F,
                CHnum_F2 = 345F,
                CHnum_F3 = 473F,
                CHnum_F4 = 524F,
                CHsum_F1 = 29473.58F,
                CHsum_F2 = 14284.51F,
                CHsum_F3 = 18845F,
                CHsum_F4 = 20616.43F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Source_Name with predicted Source_Name from sample data...\n\n");
            Console.WriteLine($"VBmaxWD_F1: {sampleData.VBmaxWD_F1}");
            Console.WriteLine($"VBmaxWD_F2: {sampleData.VBmaxWD_F2}");
            Console.WriteLine($"VBmaxWD_F3: {sampleData.VBmaxWD_F3}");
            Console.WriteLine($"VBmaxWD_F4: {sampleData.VBmaxWD_F4}");
            Console.WriteLine($"VBsumWD_F1: {sampleData.VBsumWD_F1}");
            Console.WriteLine($"VBsumWD_F2: {sampleData.VBsumWD_F2}");
            Console.WriteLine($"VBsumWD_F3: {sampleData.VBsumWD_F3}");
            Console.WriteLine($"VBsumWD_F4: {sampleData.VBsumWD_F4}");
            Console.WriteLine($"VBWL_F1: {sampleData.VBWL_F1}");
            Console.WriteLine($"VBWL_F2: {sampleData.VBWL_F2}");
            Console.WriteLine($"VBWL_F3: {sampleData.VBWL_F3}");
            Console.WriteLine($"VBWL_F4: {sampleData.VBWL_F4}");
            Console.WriteLine($"CHnum_F1: {sampleData.CHnum_F1}");
            Console.WriteLine($"CHnum_F2: {sampleData.CHnum_F2}");
            Console.WriteLine($"CHnum_F3: {sampleData.CHnum_F3}");
            Console.WriteLine($"CHnum_F4: {sampleData.CHnum_F4}");
            Console.WriteLine($"CHsum_F1: {sampleData.CHsum_F1}");
            Console.WriteLine($"CHsum_F2: {sampleData.CHsum_F2}");
            Console.WriteLine($"CHsum_F3: {sampleData.CHsum_F3}");
            Console.WriteLine($"CHsum_F4: {sampleData.CHsum_F4}");
            Console.WriteLine($"\n\nPredicted Source_Name value {predictionResult.Prediction} \nPredicted Source_Name scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
